export const CREATE_DELIVERY_REQUEST = "CREATE_DELIVERY_REQUEST";
export const CREATE_DELIVERY_SUCCESS = "CREATE_DELIVERY_SUCCESS";
export const CREATE_DELIVERY_FAIL = "CREATE_DELIVERY_FAIL";
export const CREATE_DELIVERY_RESET = "CREATE_DELIVERY_RESET";

export const GET_DELIVERY_REQUEST = "GET_DELIVERY_REQUEST";
export const GET_DELIVERY_SUCCESS = "GET_DELIVERY_SUCCESS";
export const GET_DELIVERY_FAIL = "GET_DELIVERY_FAIL";

export const DELETE_DELIVERY_REQUEST = "DELETE_DELIVERY_REQUEST";
export const DELETE_DELIVERY_SUCCESS = "DELETE_DELIVERY_SUCCESS";
export const DELETE_DELIVERY_FAIL = "DELETE_DELIVERY_FAIL";
export const DELETE_DELIVERY_RESET = "DELETE_DELIVERY_RESET";

export const UPDATE_DELIVERY_REQUEST = "UPDATE_DELIVERY_REQUEST";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_FAIL = "UPDATE_DELIVERY_FAIL";
export const UPDATE_DELIVERY_RESET = "UPDATE_DELIVERY_RESET";
