export const CREATE_TESTIMONY_REQUEST = "CREATE_TESTIMONY_REQUEST";
export const CREATE_TESTIMONY_SUCCESS = "CREATE_TESTIMONY_SUCCESS";
export const CREATE_TESTIMONY_FAIL = "CREATE_TESTIMONY_FAIL";
export const CREATE_TESTIMONY_RESET = "CREATE_TESTIMONY_RESET";

export const GET_TESTIMONY_REQUEST = "GET_TESTIMONY_REQUEST";
export const GET_TESTIMONY_SUCCESS = "GET_TESTIMONY_SUCCESS";
export const GET_TESTIMONY_FAIL = "GET_TESTIMONY_FAIL";

export const DELETE_TESTIMONY_REQUEST = "DELETE_TESTIMONY_REQUEST";
export const DELETE_TESTIMONY_SUCCESS = "DELETE_TESTIMONY_SUCCESS";
export const DELETE_TESTIMONY_FAIL = "DELETE_TESTIMONY_FAIL";
export const DELETE_TESTIMONY_RESET = "DELETE_TESTIMONY_RESET";

export const UPDATE_TESTIMONY_REQUEST = "UPDATE_TESTIMONY_REQUEST";
export const UPDATE_TESTIMONY_SUCCESS = "UPDATE_TESTIMONY_SUCCESS";
export const UPDATE_TESTIMONY_FAIL = "UPDATE_TESTIMONY_FAIL";
export const UPDATE_TESTIMONY_RESET = "UPDATE_TESTIMONY_RESET";
